

//Install "en" translations
ws.installLanguage({
  language: 'en',
  entries: {
    confirmNewChart:
      'Are you sure you want to abandon the current chart and start over?',
    previewChart: 'Preview Chart',
    newChart: 'New Chart',
    saveProject: 'Save Project',
    loadProject: 'Load Project',
    exportPNG: 'Export as PNG',
    exportJPEG: 'Export as JPEG',
    exportSVG: 'Export as SVG',
    exportPDF: 'Export as PDF',
    loadCloud: 'Load From Cloud',
    saveCloud: 'Save To Cloud',
    help: 'Help',
    licenseInfo: 'License Information',
    stepDone: 'Done',
    stepStart: 'Start',
    stepImport: 'Import',
    stepTemplates: 'Templates',
    stepCustomize: 'Customize',
    stepExport: 'Export',
    stepData: 'Data',
    doneCaption: 'Close & Generate Chart',
    dgDeleteRow: 'Really delete the selected rows?',
    dgWithSelected: 'With Selection:',
    dgImportBtn: 'IMPORT',
    dgExportBtn: 'EXPORT DATA',
    dgNewBtn: 'Clear',
    dgAddRow: 'ADD ROW',
    dgDataImported: 'Data imported',
    dgDataImporting: 'Importing data',
    dgNewCol: 'New Column',
    dgSortAsc: 'Sort Ascending',
    dgSortDec: 'Sort Descending',
    dgSortAscMonth: 'Sort as Month Names Ascending',
    dgSortDecMonth: 'Sort as Month Names Decending',
    dgDelCol: 'Delete Column',
    dgDelColConfirm: 'Really delete the column?',
    dgInsColBefore: 'Insert Column Before',
    dgInsColAfter: 'Insert Column After',
    customizeSimple: 'SIMPLE',
    customizeAdvanced: 'ADVANCED',
    customizeCustomCode: 'CUSTOM CODE',
    customizePreview: 'PREVIEW OPTIONS',
    'option.cat.title': 'Titles',
    'option.cat.chart': 'Chart',
    'option.subcat.dimension': 'Dimensions',
    'option.subcat.title': 'Title',
    'option.subcat.appearance': 'Appearance',
    'option.subcat.tooltip': 'Tooltip',
    'option.subcat.credit': 'Credits',
    'option.subcat.titles': 'Main titles',
    'option.cat.general': 'General',
    'option.subcat.size': 'Chart size',
    'option.subcat.interaction': 'Interaction',
    'option.cat.appearance': 'Appearance',
    'option.subcat.fonts': 'Fonts',
    'option.subcat.titlestyle': 'Title Style',
    'option.subcat.seriescolors': 'Series Colors',
    'option.subcat.chartarea': 'Chart Area',
    'option.subcat.plotarea': 'Plot Area',
    'option.cat.axes': 'Axes',
    'option.subcat.axessetup': 'Axes Setup',
    'option.subcat.xaxis': 'X Axis',
    'option.subcat.yaxis': 'Y Axis',
    'option.cat.series': 'Data Series',
    'option.cat.labels': 'Value Labels',
    'option.subcat.labels': 'Value Labels',
    'option.cat.legend': 'Legend',
    'option.subcat.general': 'General',
    'option.subcat.placement': 'Placement',
    'option.subcat.legendappearance': 'Appearance',
    'option.cat.tooltip': 'Tooltip',
    'option.subcat.colorborder': 'Color and Border',
    'option.cat.export': 'Export',
    'option.cat.exporting': 'Exporting',
    'option.cat.localization': 'Localization',
    'option.subcat.numberformat': 'Number formatting',
    'option.subcat.exportbutton': 'Exporting Menu',
    'option.subcat.zoombutton': 'Zoom button',
    'option.cat.credits': 'Credits',
    'option.series.label': 'Series Labels',
    'option.text.series.label.enabled': 'Series label',
    'option.tooltip.series.label.enabled':
      'Enable or disable the series label. Series labels are placed as close to the series as possible in a natural way, seeking to avoid other series. The goal of this feature is to make the chart more easily readable, like if a human designer placed the labels in the optimal position.',
    'option.text.series.label.style': 'Series label style',
    'options.tooltip.series.label.style': '',
    'option.text.title.text': 'Chart title',
    'option.tooltip.title.text': 'The main chart title.',
    'option.text.subtitle.text': 'Chart subtitle',
    'option.tooltip.subtitle.text':
      "The chart's subtitle, normally displayed with smaller fonts below the main title.",
    'option.text.yAxis.title.text': 'Y axis title',
    'option.tooltip.yAxis.title.text':
      'The Y axis title, normally displayed vertically along the Y axis.',
    'option.text.chart.width': 'Chart width',
    'option.tooltip.chart.width':
      'An explicit width for the chart. By default (when <code>null</code>) the width is calculated from the offset width of the containing element.',
    'option.text.chart.height': 'Chart height',
    'option.tooltip.chart.height':
      "An explicit height for the chart. By default (when <code>null</code>) the height is calculated from the offset height of the containing element, or 400 pixels if the containing element's height is 0.",
    'option.text.chart.zoomType': 'Allow zooming',
    'option.tooltip.chart.zoomType':
      'Decides in what dimensions the user can zoom by dragging the mouse. Can be one of <code>x</code>, <code>y</code> or <code>xy</code>.',
    'option.text.plotOptions.series.states.inactive.opacity': 'Series Dimming',
    'option.tooltip.plotOptions.series.states.inactive.opacity':
      'Opacity of series elements (dataLabels, line, area).',
    'option.text.chart.polar': 'Polar (radar) projection',
    'option.tooltip.chart.polar':
      'When true, cartesian charts like line, spline, area and column are transformed into the polar coordinate system. Requires <code>highcharts-more.js</code>.',
    'option.text.chart.style': 'Font family',
    'option.tooltip.chart.style': 'The font to use throughout the chart',
    'option.text.title.style': 'Main title style',
    'option.tooltip.title.style': 'Styling for the main chart title',
    'option.text.subtitle.style': 'Subtitle style',
    'option.tooltip.subtitle.style':
      "Styling for the chart's subtitle, normally displayed with smaller fonts below the main title",
    'option.text.colors': 'Colors',
    'option.tooltip.colors':
      'Default colors for the data series, or for individual points in a pie series or a column series with individual colors. Colors will be picked in succession. If a color is explicitly set for each series in the <em>Data series</em> view, that color will take precedence.',
    'option.text.chart.backgroundColor': 'Background color',
    'option.tooltip.chart.backgroundColor':
      'Background color for the full chart area',
    'option.text.chart.borderWidth': 'Border width',
    'option.tooltip.chart.borderWidth':
      'The pixel width of the outer chart border.',
    'option.text.chart.borderRadius': 'Border corner radius',
    'option.tooltip.chart.borderRadius':
      'The corner radius of the outer chart border.',
    'option.text.chart.borderColor': 'Border color',
    'option.tooltip.chart.borderColor': 'The color of the outer chart border.',
    'option.text.chart.plotBackgroundColor': 'Background color',
    'option.tooltip.chart.plotBackgroundColor':
      'Background color for the plot area, the area inside the axes',
    'option.text.chart.plotBackgroundImage': 'Background image URL',
    'option.tooltip.chart.plotBackgroundImage':
      'The online URL for an image to use as the plot area background',
    'option.text.chart.plotBorderWidth': 'Border width',
    'option.tooltip.chart.plotBorderWidth':
      'The pixel width of the plot area border.',
    'option.text.chart.plotBorderColor': 'Border color',
    'option.tooltip.chart.plotBorderColor':
      'The color of the inner chart or plot area border.',
    'option.text.chart.inverted': 'Inverted axes',
    'option.tooltip.chart.inverted':
      '<p>Whether to invert the axes so that the x axis is vertical and y axis is horizontal. When true, the x axis is <a href="#xAxis.reversed">reversed</a> by default. If a bar series is present in the chart, it will be inverted automatically.</p>\r\n\r\n<p>Inverting the chart doesn\'t have an effect if there are no cartesian series in the chart, or if the chart is <a href="#chart.polar">polar</a>.</p>',
    'option.text.xAxis.title.style': 'X axis title',
    'option.tooltip.xAxis.title.style': 'Styling and text for the X axis title',
    'option.text.xAxis.title.text': 'Text',
    'option.tooltip.xAxis.title.text':
      'The actual text of the axis title. It can contain basic HTML text markup like &lt;b&gt;, &lt;i&gt; and spans with style.',
    'option.text.xAxis.type': 'Type',
    'option.tooltip.xAxis.type': 'The type of axis',
    'option.text.xAxis.opposite': 'Opposite side of chart',
    'option.tooltip.xAxis.opposite':
      'Whether to display the axis on the opposite side of the normal. The normal is on the left side for vertical axes and bottom for horizontal, so the opposite sides will be right and top respectively. This is typically used with dual or multiple axes.',
    'option.text.xAxis.margin': 'Margin',
    'option.tooltip.xaxis.margin':
      'If there are multiple axes on the same side of the chart, the pixel margin between the axes.',
    'option.text.xAxis.reversed': 'Reversed direction',
    'option.tooltip.xAxis.reversed':
      'Whether to reverse the axis so that the highest number is closest to the origin. If the chart is inverted, the x axis is reversed by default.',
    'option.text.xAxis.labels.format': 'Axis labels format',
    'option.tooltip.xAxis.labels.format':
      '<p>A format string for the axis labels. The value is available through a variable <code>{value}</code>.</p><p><b>Units</b> can be added for example like <code>{value} USD</code>.</p><p><b>Formatting</b> can be added after a colon inside the variable, for example <code>USD {value:.2f}</code> to display two decimals, or <code>{value:%Y-%m-%d}</code> for a certain time format.',
    'option.text.yAxis.title.style': 'Y axis title style',
    'option.tooltip.yAxis.title.style': 'Styling and text for the X axis title',
    'option.text.yAxis.type': 'Type',
    'option.tooltip.yAxis.type': 'The type of axis',
    'option.text.yAxis.opposite': 'Opposite side of chart',
    'option.tooltip.yAxis.opposite':
      'Whether to display the axis on the opposite side of the normal. The normal is on the left side for vertical axes and bottom for horizontal, so the opposite sides will be right and top respectively. This is typically used with dual or multiple axes.',
    'option.text.yAxis.reversed': 'Reversed direction',
    'option.tooltip.yAxis.reversed':
      'Whether to reverse the axis so that the highest number is closest to the origin. If the chart is inverted, the x axis is reversed by default.',
    'option.text.yAxis.labels.format': 'Axis labels format',
    'option.tooltip.yAxis.labels.format':
      '<p>A format string for the axis labels. The value is available through a variable <code>{value}</code>.</p><p><b>Units</b> can be added for example like <code>{value} USD</code>.</p><p><b>Formatting</b> can be added after a colon inside the variable, for example <code>USD {value:.2f}</code> to display two decimals, or <code>{value:%Y-%m-%d}</code> for a certain time format.',
    'option.text.series.type': 'Series type',
    'option.tooltip.series.type': 'The type of series',
    'option.text.series.color': 'Color',
    'option.tooltip.series.color':
      'The main color of the series. If no color is given here, the color is pulled from the array of default colors as given in the "Appearance" section.',
    'option.text.series.negativeColor': 'Negative color',
    'option.tooltip.series.negativeColor':
      'The negative color of the series below the threshold. Threshold is default zero, this can be changed in the advanced settings.',
    'option.text.series.colorByPoint': 'Color by point',
    'option.tooltip.series.colorByPoint':
      'Use one color per point. Colors can be changed in the "Appearance" section.',
    'option.text.series.dashStyle': 'Dash style',
    'option.tooltip.series.dashStyle':
      'A name for the dash style to use for the graph. Applies only to series type having a graph, like <code>line</code>, <code>spline</code>, <code>area</code> and <code>scatter</code> in  case it has a <code>lineWidth</code>. The value for the <code>dashStyle</code> include:\r\n\t\t    <ul>\r\n\t\t    \t<li>Solid</li>\r\n\t\t    \t<li>ShortDash</li>\r\n\t\t    \t<li>ShortDot</li>\r\n\t\t    \t<li>ShortDashDot</li>\r\n\t\t    \t<li>ShortDashDotDot</li>\r\n\t\t    \t<li>Dot</li>\r\n\t\t    \t<li>Dash</li>\r\n\t\t    \t<li>LongDash</li>\r\n\t\t    \t<li>DashDot</li>\r\n\t\t    \t<li>LongDashDot</li>\r\n\t\t    \t<li>LongDashDotDot</li>\r\n\t\t    </ul>',
    'option.text.series.marker.enabled': 'Enable point markers',
    'option.tooltip.series.marker.enabled':
      'Enable or disable the point marker. If <code>null</code>, the markers are hidden when the data is dense, and shown for more widespread data points.',
    'option.text.series.marker.symbol': 'Marker symbol',
    'option.tooltip.series.marker.symbol':
      '<p>A predefined shape or symbol for the marker. When null, the symbol is pulled from options.symbols. Other possible values are "circle", "square", "diamond", "triangle" and "triangle-down".</p>\r\n\r\n<p>Additionally, the URL to a graphic can be given on this form:  "url(graphic.png)". Note that for the image to be applied to exported charts, its URL needs to be accessible by the export server.</p>\r\n\r\n<p>Custom callbacks for symbol path generation can also be added to <code>Highcharts.SVGRenderer.prototype.symbols</code>. The callback is then used by its method name, as shown in the demo.</p>',
    'option.text.plotOptions.series.dataLabels.enabled':
      'Enable data labels for all series',
    'option.tooltip.plotOptions.series.dataLabels.enabled':
      'Show small labels next to each data value (point, column, pie slice etc)',
    'option.text.plotOptions.series.dataLabels.style': 'Text style',
    'option.tooltip.plotOptions.series.dataLabels.style':
      'Styles for the label.',
    'option.text.legend.enabled': 'Enable legend',
    'option.tooltip.legend.enabled': 'Enable or disable the legend.',
    'option.text.legend.layout': 'Item layout',
    'option.text.legend.labelFormat': 'Label Format',
    'option.tooltip.legend.labelFormat':
      'A format string for each legend label',
    'option.tooltip.legend.layout':
      'The layout of the legend items. Can be one of "horizontal" or "vertical".',
    'option.text.legend.align': 'Horizontal alignment',
    'option.tooltip.legend.align':
      '<p>The horizontal alignment of the legend box within the chart area. Valid values are <code>left</code>, <code>center</code> and <code>right</code>.</p>\r\n\r\n<p>In the case that the legend is aligned in a corner position, the <code>layout</code> option will determine whether to place it above/below or on the side of the plot area.</p>',
    'option.text.legend.x': 'Horizontal offset',
    'option.tooltip.legend.x':
      'The pixel offset of the legend relative to its alignment',
    'option.text.legend.verticalAlign': 'Vertical alignment',
    'option.tooltip.legend.verticalAlign':
      '<p>The vertical alignment of the legend box. Can be one of <code>top</code>, <code>middle</code> or  <code>bottom</code>. Vertical position can be further determined by the <code>y</code> option.</p>\r\n\r\n<p>In the case that the legend is aligned in a corner position, the <code>layout</code> option will determine whether to place it above/below or on the side of the plot area.</p>',
    'option.text.legend.y': 'Vertical offset',
    'option.tooltip.legend.y':
      'The pixel offset of the legend relative to its alignment',
    'option.text.legend.floating': 'Float on top of plot area',
    'option.tooltip.legend.floating':
      'When the legend is floating, the plot area ignores it and is allowed to be placed below it.',
    'option.text.legend.itemStyle': 'Text style',
    'option.tooltip.legend.itemStyle':
      'CSS styles for each legend item. Only a subset of CSS is supported, notably those options related to text.',
    'option.text.legend.itemHiddenStyle': 'Text style hidden',
    'option.tooltip.legend.itemHiddenStyle':
      'CSS styles for each legend item when the corresponding series or point is hidden. Only a subset of CSS is supported, notably those options related to text. Properties are inherited from <code>style</code> unless overridden here.',
    'option.text.legend.backgroundColor': 'Background color',
    'option.tooltip.legend.backgroundColor':
      'The background color of the legend.',
    'option.text.legend.borderWidth': 'Border width',
    'option.tooltip.legend.borderWidth':
      'The width of the drawn border around the legend.',
    'option.text.legend.borderRadius': 'Border corner radius',
    'option.tooltip.legend.borderRadius':
      'The border corner radius of the legend.',
    'option.text.legend.borderColor': 'Border color',
    'option.tooltip.legend.borderColor':
      'The color of the drawn border around the legend.',
    'option.text.tooltip.enabled': 'Enable tooltip',
    'option.tooltip.tooltip.enabled':
      'Enable or disable the tooltip. The tooltip is the information box that appears on mouse-over or touch on a point.',
    'option.text.tooltip.shared': 'Shared between series',
    'option.tooltip.tooltip.shared':
      'When the tooltip is shared, the entire plot area will capture mouse movement or touch events. Tooltip texts for series types with ordered data (not pie, scatter, flags etc) will be shown in a single bubble. This is recommended for single series charts and for tablet/mobile optimized charts.',
    'option.text.tooltip.backgroundColor': 'Background color',
    'option.tooltip.tooltip.backgroundColor':
      'The background color of the tooltip',
    'option.text.tooltip.valueSuffix': 'Value Suffix',
    'option.tooltip.tooltip.valueSuffix':
      'A string to append to each series y value',
    'option.text.tooltip.borderWidth': 'Border width',
    'option.tooltip.tooltip.borderWidth':
      '<p>The pixel width of the tooltip border.</p>\r\n\r\n<p>In <a href="http://www.highcharts.com/docs/chart-design-and-style/style-by-css">styled mode</a>, the stroke width is set in the <code>.highcharts-tooltip-box</code> class.</p>',
    'option.text.tooltip.borderRadius': 'Border corner radius',
    'option.tooltip.tooltip.borderRadius':
      'The radius of the rounded border corners.',
    'option.text.tooltip.borderColor': 'Border color',
    'option.tooltip.tooltip.borderColor':
      'The border color of the tooltip. If no color is given, the corresponding series color is used.',
    'option.text.exporting.enabled': 'Enable exporting',
    'option.tooltip.exporting.enabled':
      'Enable the context button on the top right of the chart, allowing end users to download image exports.',
    'option.text.exporting.sourceWidth': 'Exported width',
    'option.tooltip.exporting.sourceWidth':
      'The width of the original chart when exported. The pixel width of the exported image is then multiplied by the <em>Scaling factor</em>.',
    'option.text.exporting.scale': 'Scaling factor',
    'option.tooltip.exporting.scale':
      'The export scale. Note that this is overridden if width is set.',
    'option.text.exporting.offlineExporting': 'Offline Exporting',
    'option.tooltip.exporting.offlineExporting':
      'The offline-exporting module allows for image export of charts without sending data to an external server',
    'option.text.lang.decimalPoint': 'Decimal point',
    'option.tooltip.lang.decimalPoint':
      'The decimal point used for all numbers',
    'option.text.lang.thousandsSep': 'Thousands separator',
    'option.tooltip.lang.thousandsSep':
      'The thousands separator used for all numbers',
    'option.text.lang.contextButtonTitle': 'Context button title',
    'option.tooltip.lang.contextButtonTitle':
      'Exporting module menu. The tooltip title for the context menu holding print and export menu items.',
    'option.text.lang.printChart': 'Print chart',
    'option.tooltip.lang.printChart':
      'Exporting module only. The text for the menu item to print the chart.',
    'option.text.lang.downloadPNG': 'Download PNG',
    'option.tooltip.lang.downloadPNG':
      'Exporting module only. The text for the PNG download menu item.',
    'option.text.lang.downloadJPEG': 'Download JPEG',
    'option.tooltip.lang.downloadJPEG':
      'Exporting module only. The text for the JPEG download menu item.',
    'option.text.lang.downloadPDF': 'Download PDF',
    'option.tooltip.lang.downloadPDF':
      'Exporting module only. The text for the PDF download menu item.',
    'option.text.lang.downloadSVG': 'Download SVG',
    'option.tooltip.lang.downloadSVG':
      'Exporting module only. The text for the SVG download menu item.',
    'option.text.lang.resetZoom': 'Reset zoom button',
    'option.tooltip.lang.resetZoom':
      'The text for the label appearing when a chart is zoomed.',
    'option.text.credits.enabled': 'Enable credits',
    'option.tooltip.credits.enabled': 'Whether to show the credits text',
    'option.text.credits.text': 'Credits text',
    'option.tooltip.credits.text': 'The text for the credits label',
    'option.text.credits.href': 'Link',
    'option.tooltip.credits.href': 'The URL for the credits label',
      "confirmNewChart": "确定放弃当前图表并重新开始？",
      "previewChart": "预览",
      "newChart": "新建",
      "saveProject": "保存项目",
      "loadProject": "加载项目",
      "exportPNG": "导出为PNG",
      "exportJPEG": "导出为JPEG",
      "exportSVG": "导出为SVG",
      "exportPDF": "导出为PDF",
      "help": "帮助",
      "licenseInfo": "许可信息",
      "stepDone": "完成",
      "stepStart": "开始",
      "stepImport": "导入",
      "stepTemplates": "模板",
      "stepCustomize": "自定义",
      "stepExport": "导出",
      "stepData": "数据",
      "doneCaption": "关闭并生成图表",
      "dgDeleteRow": "确定删除已选行？",
      "dgWithSelected": "对已选择的行：",
      "dgImportBtn": "导入",
      "dgExportBtn": "导出",
      "dgNewBtn": "新建",
      "dgAddRow": "增加行",
      "dgDataImported": "数据已导入",
      "dgDataImporting": "数据导入中",
      "dgNewCol": "新增列",
      "dgSortAsc": "升序",
      "dgSortDec": "倒序",
      "dgSortAscMonth": "按月升序",
      "dgSortDecMonth": "按月倒序",
      "dgDelCol": "删除列",
      "dgDelColConfirm": "确定删除该列？",
      "dgInsColBefore": "前插列",
      "dgInsColAfter": "后插列",
      "customizeSimple": "简单",
      "customizeAdvanced": "高级",
      "option.cat.title": "标题",
      "option.subcat.titles": "主标题",
      "option.cat.general": "通用",
      "option.subcat.size": "图表尺寸",
      "option.subcat.interaction": "图表交互",
      "option.cat.appearance": "外观",
      "option.subcat.fonts": "字体",
      "option.subcat.titlestyle": "标题样式",
      "option.subcat.seriescolors": "系列颜色",
      "option.subcat.chartarea": "图表区域",
      "option.subcat.plotarea": "绘图区域",
      "option.cat.axes": "轴",
      "option.subcat.axessetup": "轴设置",
      "option.subcat.xaxis": "X轴",
      "option.subcat.yaxis": "Y轴",
      "option.cat.series": "数据系列",
      "option.cat.labels": "数据标签",
      "option.subcat.labels": "数据标签",
      "option.cat.legend": "图例",
      "option.subcat.general": "通用",
      "option.subcat.placement": "位置",
      "option.subcat.legendappearance": "外观",
      "option.cat.tooltip": "提示",
      "option.subcat.colorborder": "颜色和边框",
      "option.cat.exporting": "导出",
      "option.cat.localization": "本地化",
      "option.subcat.numberformat": "数值格式",
      "option.subcat.exportbutton": "导出按钮及菜单",
      "option.subcat.zoombutton": "缩放按钮",
      "option.cat.credits": "著作权",
      "option.text.title.text": "图表标题",
      "option.tooltip.title.text": "主标题",
      "option.text.subtitle.text": "副标题",
      "option.tooltip.subtitle.text": "图表的副标题，以较小的字体显示在主标题下方",
      "option.text.yAxis.title.text": "Y轴标题",
      "option.tooltip.yAxis.title.text": "Y轴标题，沿Y轴方向显示",
      "option.text.chart.width": "图表宽度",
      "option.tooltip.chart.width": "图表的确切宽度。默认(<code>null</code>)根据包含元素的偏移宽度计算。",
      "option.text.chart.height": "图表高度",
      "option.tooltip.chart.height": "图表的确切高度。默认(<code>null</code>)根据包含元素的偏移高度计算，若包含元素高度为0则采用400像素。",
      "option.text.chart.zoomType": "允许缩放",
      "option.tooltip.chart.zoomType": "用户可以通过鼠标拖拽缩放的维度。可选值为：<code>x</code>, <code>y</code> or <code>xy</code>.",
      "option.text.chart.polar": "极坐标(雷达)投影",
      "option.tooltip.chart.polar": "若勾选，线图、样条图、堆积图和柱状图将会按照极坐标系统进行转换。需要<code>highcharts-more.js</code>支持。",
      "option.text.chart.style": "所有字体",
      "option.tooltip.chart.style": "整个使用的字体",
      "option.text.title.style": "主标题样式",
      "option.tooltip.title.style": "控制主标题的样式",
      "option.text.subtitle.style": "副标题样式",
      "option.tooltip.subtitle.style": "控制副标题的样式，通常以更小的字体在主标题下方显示",
      "option.text.colors": "颜色",
      "option.tooltip.colors": "数据系列默认的颜色，或者针对饼图或柱状图单个点的颜色。色彩会被按顺序选择。如果在<em>数据系列</em>中对系列进行设置，则以之为准。",
      "option.text.chart.backgroundColor": "背景颜色",
      "option.tooltip.chart.backgroundColor": "整个图表区域的背景颜色",
      "option.text.chart.borderWidth": "边框宽度",
      "option.tooltip.chart.borderWidth": "图表外边框宽度(像素)。",
      "option.text.chart.borderRadius": "边角半径",
      "option.tooltip.chart.borderRadius": "图表外边框角半径。",
      "option.text.chart.borderColor": "边框颜色",
      "option.tooltip.chart.borderColor": "图表外边框颜色。",
      "option.text.chart.plotBackgroundColor": "背景颜色",
      "option.tooltip.chart.plotBackgroundColor": "绘图区域(坐标内区域)背景色",
      "option.text.chart.plotBackgroundImage": "背景图片链接",
      "option.tooltip.chart.plotBackgroundImage": "作为绘图区域背景图片的在线URL",
      "option.text.chart.plotBorderWidth": "边框宽度",
      "option.tooltip.chart.plotBorderWidth": "绘图区域边框宽度(像素)。",
      "option.text.chart.plotBorderColor": "边框颜色",
      "option.tooltip.chart.plotBorderColor": "绘图区域边框颜色。",
      "option.text.chart.inverted": "交换轴",
      "option.tooltip.chart.inverted": "<p>是否交换轴以使得x轴垂直而y轴水平。When true, the x axis is <a href=\"#xAxis.reversed\">reversed</a> by default. If a bar series is present in the chart, it will be inverted automatically.</p>\r\n\r\n<p>Inverting the chart doesn't have an effect if there are no cartesian series in the chart, or if the chart is <a href=\"#chart.polar\">polar</a>.</p>",
      "option.text.xAxis.title.style": "X轴标题样式",
      "option.tooltip.xAxis.title.style": "X轴标题的样式",
      "option.text.xAxis.title.text": "文本",
      "option.tooltip.xAxis.title.text": "该轴标题的具体文本。它可以含有基础的HTML标签，如:&lt;b&gt;, &lt;i&gt; ",
      "option.text.xAxis.type": "类型",
      "option.tooltip.xAxis.type": "轴的类型",
      "option.text.xAxis.opposite": "对侧显示",
      "option.tooltip.xAxis.opposite": "是否将坐标轴显示在图表的另一侧。一般来说，垂直的坐标在左侧，水平的坐标在下侧，所以另一侧相应地是指右侧和上侧。一般在双坐标或多坐标场景下使用。",
      "option.text.xAxis.reversed": "逆向显示",
      "option.tooltip.xAxis.reversed": "是否将坐标逆向以使得最大坐标值离原点最近。若图表逆向，默认将X轴逆向。",
      "option.text.xAxis.labels.format": "轴标签格式",
      "option.tooltip.xAxis.labels.format": "<p>轴标签的格式字符串。实际数据可通过变量<code>{value}</code>来获得。</p><p><b>例如可以使用<code>{value} USD</code>来增加单位。</p><p>在变量内部也可以使用冒号来对数据进行<b>格式化</b>，如:<code>USD {value:.2f}</code>可展现两位有效数字，<code>{value:%Y-%m-%d}</code>可进行日期字符串格式化。",
      "option.text.yAxis.title.style": "Y轴标题样式",
      "option.tooltip.yAxis.title.style": "Y轴标题的样式",
      "option.text.yAxis.type": "类型",
      "option.tooltip.yAxis.type": "轴的类型",
      "option.text.yAxis.opposite": "对侧显示",
      "option.tooltip.yAxis.opposite": "是否将坐标轴显示在图表的另一侧。一般来说，垂直的坐标在左侧，水平的坐标在下侧，所以另一侧相应地是指右侧和上侧。一般在双坐标或多坐标场景下使用。",
      "option.text.yAxis.reversed": "逆向显示",
      "option.tooltip.yAxis.reversed": "是否将坐标逆向以使得最大坐标值离原点最近。若图表逆向，默认将Y轴逆向。",
      "option.text.yAxis.labels.format": "轴标签格式",
      "option.tooltip.yAxis.labels.format": "<p>轴标签的格式字符串。实际数据可通过变量<code>{value}</code>来获得。</p><p><b>例如可以使用<code>{value} USD</code>来增加单位。</p><p>在变量内部也可以使用冒号来对数据进行<b>格式化</b>，如:<code>USD {value:.2f}</code>可展现两位有效数字，<code>{value:%Y-%m-%d}</code>可进行日期字符串格式化。",
      "option.text.series.type": "系列类型",
      "option.tooltip.series.type": "该系列的类型",
      "option.text.series.color": "颜色",
      "option.tooltip.series.color": "该系列的主颜色。若此处不指定，则从\"外观\"中的默认颜色中选取。",
      "option.text.series.negativeColor": "负色",
      "option.tooltip.series.negativeColor": "该系列低于阈值的负颜色。阈值默认是0，在高级设定中可以修改。",
      "option.text.series.colorByPoint": "单点着色",
      "option.tooltip.series.colorByPoint": "每一个点使用一种颜色。颜色可以在\"外观\"中修改。",
      "option.text.series.dashStyle": "短划线风格",
      "option.tooltip.series.dashStyle": "图中短划线风格。仅对具有图的系列有作用，如<code>线图</code>, <code>样条图</code>, <code>面积图</code>和<code>散点图</code>，并且具有<code>lineWidth</code>。<code>短划线风格</code>有：\r\n\t\t    <ul>\r\n\t\t    \t<li>Solid</li>\r\n\t\t    \t<li>ShortDash</li>\r\n\t\t    \t<li>ShortDot</li>\r\n\t\t    \t<li>ShortDashDot</li>\r\n\t\t    \t<li>ShortDashDotDot</li>\r\n\t\t    \t<li>Dot</li>\r\n\t\t    \t<li>Dash</li>\r\n\t\t    \t<li>LongDash</li>\r\n\t\t    \t<li>DashDot</li>\r\n\t\t    \t<li>LongDashDot</li>\r\n\t\t    \t<li>LongDashDotDot</li>\r\n\t\t    </ul>",
      "option.text.series.marker.enabled": "启用点标记",
      "option.tooltip.series.marker.enabled": "是否启用点标记。如果是<code>null</code>，若数据稠密则标记隐藏，否则展现。",
      "option.text.series.marker.symbol": "标记符号",
      "option.tooltip.series.marker.symbol": "<p>为标记预定义的形状或符号。若空，则顺序使用<code>options.symbols</code>中的符号。其他可选值为：\"circle\", \"square\", \"diamond\", \"triangle\" 以及 \"triangle-down\".</p>\r\n\r\n<p>Additionally, the URL to a graphic can be given on this form:  \"url(graphic.png)\". Note that for the image to be applied to exported charts, its URL needs to be accessible by the export server.</p>\r\n\r\n<p>Custom callbacks for symbol path generation can also be added to <code>Highcharts.SVGRenderer.prototype.symbols</code>. The callback is then used by its method name, as shown in the demo.</p>",
      "option.text.plotOptions.series.dataLabels.enabled": "对所有系列启用数据标签",
      "option.tooltip.plotOptions.series.dataLabels.enabled": "在每个数据值(点、柱、饼图切片等)旁边显示一个小标签。",
      "option.text.plotOptions.series.dataLabels.style": "文本样式",
      "option.tooltip.plotOptions.series.dataLabels.style": "标签的样式。",
      "option.text.legend.enabled": "启用图例",
      "option.tooltip.legend.enabled": "是否启用图例。",
      "option.text.legend.layout": "图例布局",
      "option.tooltip.legend.layout": "图例项的布局。可选为： \"horizontal\" , \"vertical\".",
      "option.text.legend.align": "水平对齐",
      "option.tooltip.legend.align": "<p>图例在图表区域内的水平对齐。合法取值为：<code>left</code>, <code>center</code> 以及 <code>right</code>。</p>\r\n\r\n<p>若图例对齐到角落位置，<code>layout</code>选项将决定图例展现在绘图区域的上侧或下侧。</p>",
      "option.text.legend.x": "水平偏移",
      "option.tooltip.legend.x": "图例相较于它的对齐的偏移量(像素)",
      "option.text.legend.verticalAlign": "垂直对齐",
      "option.tooltip.legend.verticalAlign": "<p>图例的垂直对齐。合法取值为：<code>top</code>, <code>middle</code> 或  <code>bottom</code>。垂直位置可以通过<code>y</code>选项进一步调整。</p>\r\n\r\n<p>若图例对齐到角落位置，<code>layout</code>选项将决定图例展现在绘图区域的上侧或下侧。</p>",
      "option.text.legend.y": "垂直偏移",
      "option.tooltip.legend.y": "图例相较于它的对齐的偏移量(像素)",
      "option.text.legend.floating": "在绘图区域内显示",
      "option.tooltip.legend.floating": "若勾选，则绘图区域不会考虑图例，且绘图可能覆盖图例。",
      "option.text.legend.itemStyle": "文本样式",
      "option.tooltip.legend.itemStyle": "每个图例项的CSS样式。仅支持CSS的一个子集，特别是和文本相关的选项。",
      "option.text.legend.itemHiddenStyle": "隐藏时文本样式",
      "option.tooltip.legend.itemHiddenStyle": "若系列或点隐藏了，其相关的图例项的CSS样式。仅支持CSS的一个子集，特别是和文本相关的选项。除非此处配置，否则属性从<code>style</code>继承。",
      "option.text.legend.backgroundColor": "背景颜色",
      "option.tooltip.legend.backgroundColor": "图例的背景颜色。",
      "option.text.legend.borderWidth": "边框宽度",
      "option.tooltip.legend.borderWidth": "图例边框的宽度。",
      "option.text.legend.borderRadius": "边框角半径",
      "option.tooltip.legend.borderRadius": "图例的边框角半径。",
      "option.text.legend.borderColor": "边框颜色",
      "option.tooltip.legend.borderColor": "图例边框的颜色。",
      "option.text.tooltip.enabled": "启用提示",
      "option.tooltip.tooltip.enabled": "是否启用提示。提示指的是当鼠标悬停或者触摸一个点时显示的信息框。",
      "option.text.tooltip.shared": "系列间共享",
      "option.tooltip.tooltip.shared": "若勾选，整个绘图区域将捕获鼠标移动或者触摸事件。具有有序数据的系列(非饼图、散点图等)的提示信息将在同一个信息框中展现。推荐对于单系列以及为移动设备优化的图表启用。",
      "option.text.tooltip.backgroundColor": "背景颜色",
      "option.tooltip.tooltip.backgroundColor": "提示框的背景颜色",
      "option.text.tooltip.borderWidth": "边框宽度",
      "option.tooltip.tooltip.borderWidth": "<p>提示边框的宽度(像素)。</p>\r\n\r\n<p>In <a href=\"http://www.highcharts.com/docs/chart-design-and-style/style-by-css\">styled mode</a>, the stroke width is set in the <code>.highcharts-tooltip-box</code> class.</p>",
      "option.text.tooltip.borderRadius": "边框角半径",
      "option.tooltip.tooltip.borderRadius": "提示框的边框角半径。",
      "option.text.tooltip.borderColor": "边框颜色",
      "option.tooltip.tooltip.borderColor": "提示框边框颜色。若不设置，则使用与之关联的系列的颜色。",
      "option.text.exporting.enabled": "启用导出",
      "option.tooltip.exporting.enabled": "若勾选，则启用图表右上角的上下文按钮以允许终端用户以不同格式下载图表。",
      "option.text.exporting.sourceWidth": "导出宽度",
      "option.tooltip.exporting.sourceWidth": "导出时原图的宽度。导出后的图片宽度(像素)等于该值乘以<em>缩放因子</em>。",
      "option.text.exporting.scale": "缩放因子",
      "option.tooltip.exporting.scale": "导出时的缩放因子. 若宽度已经设置，则该设置无效。",
      "option.text.lang.decimalPoint": "小数点",
      "option.tooltip.lang.decimalPoint": "所有数字使用的小数点",
      "option.text.lang.thousandsSep": "千位分隔符",
      "option.tooltip.lang.thousandsSep": "所有数字使用的千位分隔符",
      "option.text.lang.contextButtonTitle": "上下文按钮标题",
      "option.tooltip.lang.contextButtonTitle": "导出模块菜单。包含打印和导出菜单项的提示框标题。",
      "option.text.lang.printChart": "打印图表",
      "option.tooltip.lang.printChart": "仅用于导出模块。打印图表菜单项的文本内容。",
      "option.text.lang.downloadPNG": "下载PNG",
      "option.tooltip.lang.downloadPNG": "仅用于导出模块。PNG下载菜单项的文本内容。",
      "option.text.lang.downloadJPEG": "下载JPEG",
      "option.tooltip.lang.downloadJPEG": "仅用于导出模块。JPEG下载菜单项的文本内容。",
      "option.text.lang.downloadPDF": "下载PDF",
      "option.tooltip.lang.downloadPDF": "仅用于导出模块。PDF下载菜单项的文本内容。",
      "option.text.lang.downloadSVG": "下载SVG",
      "option.tooltip.lang.downloadSVG": "仅用于导出模块。SVG下载菜单项的文本内容。",
      "option.text.lang.resetZoom": "重置缩放按钮",
      "option.tooltip.lang.resetZoom": "图表被缩放时展现的标签文本内容。",
      "option.text.credits.enabled": "启用著作权信息",
      "option.tooltip.credits.enabled": "是否显示著作权信息",
      "option.text.credits.text": "著作权信息",
      "option.tooltip.credits.text": "著作权标签文本内容。",
      "option.text.credits.href": "链接",
      "option.tooltip.credits.href": "著作权标签的URL"
  }
});
